### ISSUE TITLE
Folder of CSV files not found for document ID

### ISSUE THREAD

**Issue by alexanderadam** [pd3f/pd3f#12]
I got this error when I tried to convert a PDF:

```
INFO:root:setting up ocr
INFO:root:ocr finished successfully
INFO:pd3f.parsr_wrapper:sending PDF to Parsr
INFO:pd3f.parsr_wrapper:got response from Parsr
ERROR:rq.worker:Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 684, in perform
self._result = self._execute()
File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
return self.func(*self.args, **self.kwargs)
File "./app.py", line 273, in do_the_job
text, tables = extract(
File "/usr/local/lib/python3.8/site-packages/pd3f/export.py", line 50, in extract
input_json, tables_csv = run_parsr(
File "/usr/local/lib/python3.8/site-packages/pd3f/parsr_wrapper.py", line 86, in run_parsr
for page, table in parsr.get_tables_info():
File "/usr/local/lib/python3.8/site-packages/parsr_client/parsr_client.py", line 223, in get_tables_info
return [(table.rsplit('/')[-2], table.rsplit('/')[-1]) for table in ast.literal_eval(self.get_table(request_id=request_id).columns[0])]
File "/usr/local/lib/python3.8/ast.py", line 59, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "/usr/local/lib/python3.8/ast.py", line 47, in parse
return compile(source, filename, mode, flags,
File "", line 1
Error: Folder of CSV files not found for document ID 8fe98ff6ca95d82ef0fb214959ea78
^
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 684, in perform
self._result = self._execute()
File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
return self.func(*self.args, **self.kwargs)
File "./app.py", line 273, in do_the_job
text, tables = extract(
File "/usr/local/lib/python3.8/site-packages/pd3f/export.py", line 50, in extract
input_json, tables_csv = run_parsr(
File "/usr/local/lib/python3.8/site-packages/pd3f/parsr_wrapper.py", line 86, in run_parsr
for page, table in parsr.get_tables_info():
File "/usr/local/lib/python3.8/site-packages/parsr_client/parsr_client.py", line 223, in get_tables_info
return [(table.rsplit('/')[-2], table.rsplit('/')[-1]) for table in ast.literal_eval(self.get_table(request_id=request_id).columns[0])]
File "/usr/local/lib/python3.8/ast.py", line 59, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "/usr/local/lib/python3.8/ast.py", line 47, in parse
return compile(source, filename, mode, flags,
File "", line 1
Error: Folder of CSV files not found for document ID 8fe98ff6ca95d82ef0fb214959ea78
^
SyntaxError: invalid syntax
```

It was just in the case of a single document, though.
Otherwise it's working perfectly.
Thank you so much for pd3f! :pray:

**Comment by jfilter** [comment]
Hey Alexander, can you share the PDF, or can you reproduce the error with a document you can share? Best, Johannes

**Comment by alexanderadam** [comment]
Hi @jfilter, I'm very sorry. I tried to convert a bunch of files and I switched to [pdfsandwich](http://www.tobias-elze.de/pdfsandwich/) (mainly because [layout detection](https://github.com/pd3f/pd3f/issues/11#issue-797759593) seem to work much better than in pd3f).

I will close this then, since I'm not able to tell which document this was anyway.

Thank you for your work on pd3f, though!
